# Site settings:
site_title: '早早集市'
site_description: 'A special place all about a front-end developer'

# 主页个人信息展示
# name可以当成一个标语来使用，和左上角的name有点冲突了
name: '保持自洽'
surname: ''
professional_identity: 'you will not lose, if you do not play'
profile_picture: ''

# "About me" page's paragraphs:
关于_paragraph: 关于关于关于关于

测试__paragraph: 测试测试测测撒大

# Socials:
github_username: 'zzdaddy'
github_icon: 'github.svg'

# linkedin_username: 'test'
# linkedin_icon: 'linkedin.svg'

# instagram_username: 'test'
# instagram_icon: 'instagram.svg'

# tumblr_username: 'test'
# tumblr_icon: 'tumblr.svg'

# steam_username: 'test'
# steam_icon: 'steam.svg'

twitter_username: 'zzstudiO_O'
twitter_icon: 'twitter.svg'

# Email btn
email_address: 'gnakzz@qq.com'

# "Buy me a coffee" button:
buyMeACoffee_username: ''

# Other:
profile_picture_border: true
disable_about_me_page: false
disable_animated_underline: false
blog_preview_date_format: 'YYYY-MM-DD'
blog_preview_date_separators: '-'
max_posts_per_page: '8'
